version: 2
jobs:
  build:
    docker:
      - image: cimg/node:16.14
    working_directory: ~/knowledge
    branches:
      only:
        - main
    steps:
      - add_ssh_keys:
          fingerprints:
            - "06:f4:f6:4a:9d:43:0d:9e:0a:dd:15:33:27:0a:bf:3f"
      - checkout
      - run: echo "开始打包"
      - run: yarn -v
      - restore_cache:
          keys:
            - dependencies_circle_demo
      - run:
          name: Install
          command: yarn
      - save_cache:
          paths:
            - node_modules
          key: dependencies_circle_demo
      - run: 
          name: Build
          command: yarn build
      # - run:
      #     name: Prepare shell commands
      #     command: chmod +x deploy.sh
      # - run:
      #     name: Run Deploy to Github pages
      #     command: ./deploy.sh
      - deploy:
          name: deploy
          command: scp -vr  -o StrictHostKeyChecking=no /home/circleci/knowledge/dist/* $SSH_USER@$SSH_IP:/www/wwwroot/knowledge/
      - run: echo '部署完毕'
