version: 2
jobs:
  build:
    docker:
      - image: cimg/node:14.17
    branches:
      only:
        - main
    steps:
      - add_ssh_keys:
          fingerprints:
            - "45:46:5d:cb:3e:02:f0:a5:85:44:42:9e:5f:f8:87:7e"
      - checkout
      - run: echo "A first hello"
      - run: yarn -v
      - restore_cache:
          keys:
            - dependencies_circle_demo
      # - run:
      #     name: Install
      #     command: yarn
      # - save_cache:
      #     paths:
      #       - node_modules
      #     key: dependencies_circle_demo
      # - run: 
      #     name: Build
      #     command: yarn build
      - run: sudo apt-get update && sudo apt-get install rsync && sudo apt-get install openssh-client
      - run: ps -aux | grep ssh
      - run: echo $REMOTE_HOSTKEY >> ~/.ssh/known_hosts
      - run:
          name: quanx
          command: chmod 755  aaa.ts
      - run: ls
      - deploy:
          name: deploy
          command: |
            ls
            pwd
            if [ "${CIRCLE_BRANCH}" = "main" ]; then
              rsync -avce /home/circleci/project/aaa.ts $SSH_USER@$SSH_IP:/www/wwwroot/testbuild/
            else
              echo "Not master branch, dry run only"
            fi
      - run: echo '部署完毕啊'
# workflows:
#   version: 2
#   scheduled-workflow:
#     triggers:
#       - schedule:
#           cron: "0 0 * * *"
#           filters:
#             branches:
#               only: master
#     jobs:
#       - build    
      # - run:
      #     name: Prepare shell commands
      #     command: chmod +x deploy.sh
      # - run:
      #     name: Run Deploy to Github pages
      #     command: ./deploy.sh