version: 2
jobs:
  one:
    docker:
      - image: cimg/node:17.2
    branches:
      only:
        - main
    steps:
      - add_ssh_keys:
          fingerprints:
            - "5d:d8:5e:09:c4:cc:57:2f:e4:3b:7e:49:2a:b3:f0:24"
      - checkout
      - run: echo "A first hello"
      - run: yarn -v
      - run:
          name: Install
          command: yarn
      - run: 
          name: Build
          command: yarn build
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
