version: 2.1

jobs:
  Hello-word:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Saying Hello
          command: |
            echo 'Hello word!'
            echo 'This is the delivery pipeline'
  Fetch-Code:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      -run:
          name: "Say hello"
          command: |
            ls -al
            echo '^^^Your repo files ^^^'
  Using-Node:
    docker:
      - image: cimg/node:17.2
    steps:
      - run:
          name:  Running the Node Container
          command: |
            node -v
workflows:
  Example-Workflow:
    jobs:
      - Hello-World
      - Fetch-Code:
          requires:
            - Hello-Word
      -Using-Node:
        requires:
          - Fetch-Code
